### ISSUE TITLE
九宫格怎么设置更多的宫格，对里面每个宫格调整长宽大小

### ISSUE THREAD

**Issue by ErroristZ** [LuckDraw/lucky-canvas#1]

**Comment by buuing** [comment]
文档里可以看一下`cols`和`rows`

**Comment by buuing** [comment]
常见的九宫格可以分成`3*3`, 那你要是想调整宽高, 可以设置100*100然后通过合并单元格的方式, 此时有一个格子你希望他宽20%, 高50%, 那就让这个格子横向合并20, 纵向合并50

**Comment by ErroristZ** [comment]
你好。我使用是web，也设置了cols和rows，现在是里面的宫格不对称，不知道是在里面设置的






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuckDraw/lucky-canvas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 下午2:01
收件人:&nbsp;"LuckDraw/lucky-canvas"<lucky-canvas@noreply.github.com&gt;;
抄送:&nbsp;"Errorist"<873853298@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LuckDraw/lucky-canvas] 九宫格怎么设置更多的宫格，对里面每个宫格调整长宽大小 (#1)





 
文档里可以看一下cols和rows

**Comment by buuing** [comment]
贴一下代码, 我看看

**Comment by ErroristZ** [comment]
附件里面


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuckDraw/lucky-canvas"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月18日(星期五) 下午2:11
收件人:&nbsp;"LuckDraw/lucky-canvas"<lucky-canvas@noreply.github.com&gt;;
抄送:&nbsp;"Errorist"<873853298@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [LuckDraw/lucky-canvas] 九宫格怎么设置更多的宫格，对里面每个宫格调整长宽大小 (#1)





 
贴一下代码, 我看看

**Comment by buuing** [comment]
我是在github上回复你的, 看不到邮件

**Comment by ErroristZ** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<div id="my-lucky"></div>
<script src="https://cdn.jsdelivr.net/npm/lucky-canvas/umd.min.js"></script>
<script>
    let luckyNum = 1
    // 创建九宫格抽奖
    let luckyGrid = new LuckyCanvas.LuckyGrid({
        el: '#my-lucky',
        width: '1280px',
        height: '800px'
    }, {
        rows: 4,
        cols: 7,
        blocks: [
            { padding: '15px', background: '#ffc27a', borderRadius: 28 },
            { padding: '4px', background: '#ff4a4c', borderRadius: 23 },
            { padding: '4px', background: '#ff625b', borderRadius: 20 },
        ],
        button: {
            x: 3, y: 1.5,
            background: 'linear-gradient(270deg, #FFDCB8, #FDC689)',
            shadow: '0 5 1 #e89b4f',
            fonts: [
                { text: `${luckyNum} 次`, fontColor: '#fff', top: '73%', fontSize: '11px' },
            ],
            imgs: [
                { src: 'https://100px.net/assets/img/button.2f4ac3e9.png', width: '65%', top: '12%' },
                { src: 'https://100px.net/assets/img/button.2f4ac3e9.png', width: '50%', top: '73%' }
            ]
        },
        activeStyle: {
            background: 'linear-gradient(270deg, #FFDCB8, #FDC689)',
            shadow: ''
        },
        defaultConfig: {
            gutter: 5,
        },
        defaultStyle: {
            borderRadius: 15,
            fontColor: '#DF424B',
            fontSize: '14px',
            textAlign: 'center',
            background: '#fff',
            shadow: '0 5 1 #ebf1f4'
        },
        start () {
            if (!luckyNum) return alert('还剩0次抽奖机会')
            luckyGrid.play()
            setTimeout(() => {
                luckyGrid.stop(Math.random() * 18 >> 0)
            }, 2000)
        },
        end (prize) {
            alert(`恭喜你获得大奖: ${prize.name}`)
            luckyNum--
            luckyGrid.button.fonts[0].text = `${luckyNum} 次`
        }
    })
    // 模拟接口异步请求奖品列表
    setTimeout(() => {
        const prizes = []
        const data = [
            { name: '00元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '10元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '20元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '30元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '40元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '50元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '60元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '61元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '62元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '63元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '53元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '43元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '33元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '23元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '13元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '03元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '02元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' },
            { name: '01元红包', img: 'https://100px.net/assets/img/4.425ab3c6.png' }
        ]
        let axis = [[0, 0], [1, 0], [2, 0], [3, 0], [4, 0], [5, 0], [6, 0], [6, 1], [6, 2], [6, 3], [5, 3], [4, 3], [3, 3], [2, 3], [1, 3], [0, 3], [0, 2], [0, 1]]
        for (let i = 0; i < 18; i++) {
            let item = data[i]
            prizes.push({
                name: item.name,
                index: i, x: axis[i][0], y: axis[i][1],
                fonts: [{ text: item.name, top: '70%' }],
                imgs: [{ src: item.img, width: '53%', top: '8%' }]
            })
        }
        luckyGrid.prizes = prizes
    })
</script>
</body>
</html>

**Comment by buuing** [comment]
我看到的效果挺好啊, 有什么不对吗

**Comment by ErroristZ** [comment]
我就想调整宫格的自定义大小和样式




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "朝游夕宴"<notifications@github.com&gt;; 
发送时间: 2020年12月18日(星期五) 下午2:22
收件人: "LuckDraw/lucky-canvas"<lucky-canvas@noreply.github.com&gt;; 
抄送: "Errorist"<873853298@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [LuckDraw/lucky-canvas] 九宫格怎么设置更多的宫格，对里面每个宫格调整长宽大小 (#1)





 
我看到的效果挺好啊, 有什么不对吗

**Comment by buuing** [comment]
你的描述太过于模糊, 或许你的脑海里已经有了规划, 但请说清楚你想配置什么样的, 或画图通过github发给我

**Comment by ErroristZ** [comment]
好的好的。我先整理好，谢谢您了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "朝游夕宴"<notifications@github.com&gt;; 
发送时间: 2020年12月18日(星期五) 下午2:26
收件人: "LuckDraw/lucky-canvas"<lucky-canvas@noreply.github.com&gt;; 
抄送: "Errorist"<873853298@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [LuckDraw/lucky-canvas] 九宫格怎么设置更多的宫格，对里面每个宫格调整长宽大小 (#1)





 
你的描述太过于模糊, 或许你的脑海里已经有了规划, 但请说清楚你想配置什么样的, 或画图通过github发给我
