### ISSUE TITLE
vue3和typescript结合起来怎样使用

### ISSUE THREAD

**Issue by XiaoLizi29** [LuckDraw/lucky-canvas#102]
使用的是vue3和typescript,但是这个插件好像不支持typescript

**Comment by xiang12383** [comment]
老板有空帮弄个ts支持啊，谢谢了，

**Comment by buuing** [comment]
> 老板有空帮弄个ts支持啊，谢谢了，

实在是太忙了呀, 最近刚把源码包的ts描述文件导出来

**Comment by buuing** [comment]
最新版`v3.4.7`已增加ts描述文件
