### ISSUE TITLE
打扰 大佬 请问能分享源码嘛？ 

### ISSUE THREAD

**Issue by zhanxinpeng** [LuckDraw/lucky-canvas#12]

**Comment by zhanxinpeng** [comment]
好的 谢谢 用于个人学习但是会注意保护&nbsp; &nbsp;您是通过邮件发源码还是什么？






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuckDraw/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午3:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [LuckDraw/lucky-canvas] 打扰 大佬 请问能分享源码嘛？  (#12)





 
可以分享, 注明出处

**Comment by buuing** [comment]
这个仓库就是全部的源码
