### ISSUE TITLE
vw单位适配

### ISSUE THREAD

**Issue by zhch-hong** [LuckDraw/lucky-canvas#15]
我找到了这个方法，并在其中添加的一行代码vw: (n: number) => (window.screen.width / 100) * n，但是并没有效果
`
  /**
   * 转换单位
   * @param { string } value 将要转换的值
   * @param { number } denominator 分子
   * @return { number } 返回新的字符串
   */
  protected changeUnits(value: string, denominator = 1): number {
    return Number(
      value.replace(/^([-]*[0-9.]*)([a-z%]*)$/, (value, num, unit) => {
        const unitFunc = {
          "%": (n: number) => n * (denominator / 100),
          px: (n: number) => n * 1,
          rem: (n: number) => n * this.htmlFontSize,
          vw: (n: number) => (window.screen.width / 100) * n, // 添加这一行代码，编译后无效
        }[unit];
        if (unitFunc) return unitFunc(num);
        // 如果找不到默认单位, 就交给外面处理
        const otherUnitFunc = this.config.unitFunc;
        return otherUnitFunc ? otherUnitFunc(num, unit) : num;
      })
    );
  }
`

**Comment by buuing** [comment]
嗯嗯, 今晚我看一下

**Comment by zhch-hong** [comment]
> 嗯嗯, 今晚我看一下

谢谢，修复时麻烦回复一下哈

**Comment by buuing** [comment]
> 谢谢，修复时麻烦回复一下哈

行, 你加一下我的微信`new_ldq`有情况我说给你

**Comment by buuing** [comment]
你可以这么用, `unitFunc`会直接传递进去, 你无需重新打包

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div id="my-lucky"></div>
    <div style="background: pink; width: 50vw;">50vw</div>
    <script src="https://cdn.jsdelivr.net/npm/lucky-canvas@1.5/dist/lucky-canvas.umd.min.js"></script>
    <script>
        let luckyWheel = new LuckyCanvas.LuckyWheel({
            el: '#my-lucky',
            width: '50vw',
            height: '50vw',
            unitFunc: (num, unit) => {
                if (unit === 'vw') {
                    return (window.innerWidth / 100) * num
                }
            },
        }, {
            blocks: [{ padding: '10px', background: 'pink' }],
        })
    </script>
</body>
</html>
```

**Comment by zhch-hong** [comment]
> 你可以这么用, `unitFunc`会直接传递进去, 你无需重新打包
> 
> ```
> <!DOCTYPE html>
> <html lang="en">
> <head>
>     <meta charset="UTF-8">
>     <meta http-equiv="X-UA-Compatible" content="IE=edge">
>     <meta name="viewport" content="width=device-width, initial-scale=1.0">
>     <title>Document</title>
> </head>
> <body>
>     <div id="my-lucky"></div>
>     <div style="background: pink; width: 50vw;">50vw</div>
>     <script src="https://cdn.jsdelivr.net/npm/lucky-canvas@1.5/dist/lucky-canvas.umd.min.js"></script>
>     <script>
>         let luckyWheel = new LuckyCanvas.LuckyWheel({
>             el: '#my-lucky',
>             width: '50vw',
>             height: '50vw',
>             unitFunc: (num, unit) => {
>                 if (unit === 'vw') {
>                     return (window.innerWidth / 100) * num
>                 }
>             },
>         }, {
>             blocks: [{ padding: '10px', background: 'pink' }],
>         })
>     </script>
> </body>
> </html>
> ```

果然可以，谢谢
