### ISSUE TITLE
转盘指针大小没有自适应

### ISSUE THREAD

**Issue by zhch-hong** [LuckDraw/lucky-canvas#16]
无论转盘的width height如何变化，指针的大小并没有改变，当width height不够大时导致奖品扇形区域被遮挡严重

**Comment by buuing** [comment]
指针的大小取决于当前button的半径, 你看一下按钮半径设置的是一个固定值, 还是百分比

**Comment by zhch-hong** [comment]
> 指针的大小取决于当前button的半径, 你看一下按钮半径设置的是一个固定值, 还是百分比

看到了，是设置的固定值，改为百分比就好了
