### ISSUE TITLE
请问下对接API，怎么根据API返回的数据指定到对应宫格

### ISSUE THREAD

**Issue by ErroristZ** [LuckDraw/lucky-canvas#5]
请问下对接API，怎么根据API返回的数据指定到对应宫格

**Comment by buuing** [comment]
通过`stop(中奖索引)`来指定抽奖停止的位置

**Comment by ErroristZ** [comment]
明白了。你真棒

**Comment by buuing** [comment]
🤣**用的顺手可以点个 `star` 支持一下**

**Comment by ErroristZ** [comment]
已点

**Comment by ErroristZ** [comment]
请问下宫格里面怎么才能使用GIF动态图

**Comment by buuing** [comment]
> 请问下宫格里面怎么才能使用GIF动态图

我没试过`gif`, 你可以试一下

**Comment by ErroristZ** [comment]
我试了，没反应，不动

**Comment by buuing** [comment]
> 我试了，没反应，不动

嗯, 那就是目前还不支持, 抽奖是基于`canvas`封装的, 如果我重新绘制图片大概会导致`gif`回到初始动画?
因为抽奖旋转的时候, 每一秒大概都要绘制`60`次, 后期不忙的时候我尝试一下

**Comment by ErroristZ** [comment]
好的，谢谢了
