### ISSUE TITLE
ios-大转盘-转动时卡顿

### ISSUE THREAD

**Issue by wangzhengcheng1994** [LuckDraw/lucky-canvas#8]
如题，测试机型版本11.4.1  机型6p 转盘转动时有卡顿。

**Comment by buuing** [comment]
加我微信`new_ldq`, 录个屏我瞅瞅

**Comment by Goofy007** [comment]
你们是哪个公司bug抄送给我干啥== =




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "LuckDraw/lucky-canvas"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月13日(星期二) 下午4:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [LuckDraw/lucky-canvas] ios-大转盘-转动时卡顿 (#8)





 
加我微信new_ldq, 录个屏我瞅瞅

**Comment by buuing** [comment]
> 你们是哪个公司bug抄送给我干啥== =

.......小兄弟, 这是github自带的功能, 你点了watch, 出现issues一类的都会自动推送, 多看看github功能介绍

**Comment by Goofy007** [comment]
你们啥公司 给钱多吗&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月13日(星期二) 下午4:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [LuckDraw/lucky-canvas] ios-大转盘-转动时卡顿 (#8)





  
你们是哪个公司bug抄送给我干啥== =
  
.......小兄弟, 这是github自带的功能, 你点了watch, 出现issues一类的都会自动推送, 多看看github功能介绍

**Comment by buuing** [comment]
> 你们啥公司 给钱多吗&nbsp;

这个是我个人的开源项目, 不是公司项目, 谁会把公司项目放在github上面

**Comment by buuing** [comment]
排查完毕, 不是卡顿, `(速度太小 && 停止时间过大)`造成的
