### ISSUE TITLE
vue-luck-draw 好像没有 ts 定义？

### ISSUE THREAD

**Issue by lizy0329** [LuckDraw/lucky-canvas#80]
- 版本号：3.4.5

- 平台信息：windows 10

- 详细描述：

查看 node_modules 中 vue-luck-draw  都没发现 ts 定义文件

**Comment by buuing** [comment]
额, 确实没有, 但是欢迎pr

**Comment by lizy0329** [comment]
> 额, 确实没有, 但是欢迎pr

luck-canvas 不是 ts 写的么？

**Comment by buuing** [comment]
哈哈哈, 只是ts开发的, 没写类型描述文件

**Comment by lizy0329** [comment]
我估计你将 lucky-canvas/src/types 文件上传到 npm 上就行了吧

我看文件内还差了 play stop 的定义？

**Comment by buuing** [comment]
`src/types` 下面的文件还得稍微改动改动, 我晚上看看

**Comment by accardo** [comment]
强烈要求搞一个

**Comment by buuing** [comment]
> 强烈要求搞一个

😂好的, 尽快
