### ISSUE TITLE
手机适配样式问题

### ISSUE THREAD

**Issue by Cecilia3377** [LuckDraw/lucky-canvas#87]
有人遇到手机移动端适配问题吗？
`
prizes.push({
          x: item[0],
          y: item[1],
          fonts: [
            { text: data.prizes[index].name || '再接再励', wordWrap: false, top: '227px', fontSize: '30px' }
          ],
          isWin: data.prizes[index].ticketForm === 'ADD_CUSTOMER_SERVICE',
          imgs: [
            {
              width: '166px',
              height: '166px',
              top: '40px',
              src: data.prizes[index].img || this.defaultImgSrc
            }
          ]
        })
`
一样的代码；在 oppo 手机上显示的就特别的大；在chrome模拟器中也是很大；如果按照UI的尺寸写了；在大部分手机上就会显示的特别小；单位是px；有什么解决办法吗

**Comment by buuing** [comment]
h5页面是嘛

**Comment by buuing** [comment]
组件的宽度和高度你设置了吗, 而且你这个给的数值会不会太大了, 100多px?

**Comment by edk24** [comment]
原因是oppo还是vivo部分机型是2倍分辨率, 使用vw或者百分百可以解决适配问题
