### ISSUE TITLE
图片加载失败

### ISSUE THREAD

**Issue by 544211707** [LuckDraw/lucky-canvas#89]
原例子里被注释掉的按钮图片代码，启用时报错，也就是不能加载图片，是为什么呢？
`imgs: [{ src: require('./img/button.png'), width: '65%', top: '-50%' }]`
本人比较小白，上网查了好多种方法了都不成功，求指导，谢谢
用的是vue3，跑之前装了依赖，npm run vue3build 和 vue3serve

报错：
[object%20Module]:1 GET http://localhost:8081/[object%20Module] 404 (Not Found)
Image (async)
eval @ lucky-canvas.cjs.min.js:16
t.loadImg @ lucky-canvas.cjs.min.js:16
eval @ lucky-canvas.cjs.min.js:16
eval @ lucky-canvas.cjs.min.js:16
eval @ lucky-canvas.cjs.min.js:16
eval @ lucky-canvas.cjs.min.js:16
n @ lucky-canvas.cjs.min.js:16
o.loadAndCacheImg @ lucky-canvas.cjs.min.js:16
eval @ lucky-canvas.cjs.min.js:16
eval @ lucky-canvas.cjs.min.js:16
eval @ lucky-canvas.cjs.min.js:16
o.init @ lucky-canvas.cjs.min.js:16
o @ lucky-canvas.cjs.min.js:16
initLucky @ LuckyWheel.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[3].use[0]:54
mounted @ LuckyWheel.vue?./node_modules/vue-loader/dist/index.js??ruleSet[1].rules[3].use[0]:44
callWithErrorHandling @ runtime-core.esm-bundler.js:267
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:276
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:3013
flushPostFlushCbs @ runtime-core.esm-bundler.js:467
render @ runtime-core.esm-bundler.js:5903
mount @ runtime-core.esm-bundler.js:4185
app.mount @ runtime-dom.esm-bundler.js:1451
eval @ vue3.js:13
./example/vue3.js @ index.js:29
__webpack_require__ @ index.js:731
(anonymous) @ index.js:1776
(anonymous) @ index.js:1782
webpackUniversalModuleDefinition @ index.js:17
(anonymous) @ index.js:18
lucky-canvas.cjs.min.js:16 buttons[3].imgs[0] => '[object Module]' 图片加载失败

**Comment by 544211707** [comment]
解决了，在configvue3 里添加?esModule=false
[https://img2020.cnblogs.com/blog/1563155/202005/1563155-20200525230619774-307941134.png](url)

**Comment by 544211707** [comment]
再问一个问题，我好像没有看到居中可设置，是否不可以居中呢？
另外感谢贵方提供的非常优秀的案例~

**Comment by buuing** [comment]
> 再问一个问题，我好像没有看到居中可设置，是否不可以居中呢？
> 另外感谢贵方提供的非常优秀的案例~

上午太忙了, 没看到
居中? 你是指的哪里居中?

**Comment by 544211707** [comment]
没关系的，感谢您的回复。
就是整个转盘，可以放到网页靠顶部的中央吗？

**Comment by buuing** [comment]
> 没关系的，感谢您的回复。
> 就是整个转盘，可以放到网页靠顶部的中央吗？

可以啊, 你直接调整整个抽奖组件的css样式即可

**Comment by 544211707** [comment]
> > 没关系的，感谢您的回复。
> > 就是整个转盘，可以放到网页靠顶部的中央吗？
> 
> 可以啊, 你直接调整整个抽奖组件的css样式即可

好的，我看一下，谢谢

**Comment by buuing** [comment]
嗯嗯\(^o^)/
